import "./globals.css";

export const metadata = {
  title: "MOJITO",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en-US">
      <body>{children}</body>
    </html>
  );
}
